# This workflow installs the latest version of Terraform CLI. On pull request events, this workflow will run
# `terraform init`, `terraform fmt`, and `terraform plan`.
#
# Documentation for `hashicorp/setup-terraform` is located here: https://github.com/hashicorp/setup-terraform

name: 'Terraform'

on:
  push:
    branches: ["**"]

jobs:
  test:
    uses: sil-org/workflows/.github/workflows/terraform.yml@main
    with:
      terraform-version: '~> 1.5'
      test-dir: test

  tftest:
    name: 'Terraform Test'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # terraform test requires >= 1.7
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.5"

    - name: Terraform Test
      run: |
        terraform -chdir=test init
        terraform -chdir=test test -verbose
