name: Terraform

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    uses: sil-org/workflows/.github/workflows/terraform.yml@main
    with:
      # validate with the latest patch of the earliest minor version allowed by required_version in versions.tf
      terraform-version: '~> 1.0.0'
      test-dir: 'test'
